# Generated by Django 4.2.1 on 2023-05-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stych', '0002_hub_order_sku_remove_tailor_id_tailor_tailor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailor',
            name='user',
        ),
    ]
