# Generated by Django 4.2.1 on 2023-05-14 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stych', '0004_tailor_user_alter_tailor_tailor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='tailor_availability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='tailor_id',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='tailor_payout',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
