# Generated by Django 4.2.1 on 2023-05-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stych', '0005_alter_tailor_tailor_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='hub_capacity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='assigned_tailor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_info',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Hub_Inventory',
        ),
        migrations.DeleteModel(
            name='Order_Item',
        ),
    ]
