# Generated by Django 4.2.1 on 2023-05-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stych', '0006_remove_order_item_order_remove_order_item_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='sku_description',
        ),
        migrations.AddField(
            model_name='sku',
            name='sku_size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
