# Generated by Django 4.2.1 on 2023-05-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stych', '0007_remove_sku_sku_description_sku_sku_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completion_time',
        ),
        migrations.AlterField(
            model_name='tailor',
            name='tailor_payout',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
