# Generated by Django 4.2.1 on 2023-05-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stych', '0008_remove_order_completion_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailor',
            name='tailor_availability',
        ),
    ]
