# Generated by Django 4.2.1 on 2023-05-16 16:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stych', '0010_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='tailor_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
    ]
