# Generated by Django 4.2.1 on 2023-05-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stych', '0011_alter_tailor_tailor_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='tailor_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
