# Generated by Django 4.2.1 on 2023-05-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stych', '0013_tailor_sku_units_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='sku_units_worked',
            field=models.JSONField(default=dict),
        ),
    ]
